# Photoshop Scanner Bridge Configuration (Auto-saved)
naps2=
driver=twain
device=CanoScan LiDE 400
nativeui=off
deskew=on
dpi=300
bitdepth=color
source=glass
pagesize=a4
format=jpg
openinps=on
keepfiles=on
crop_x=0
crop_y=0
crop_w=1
crop_h=0.2567
skew_angle=0
args=-o "{OUT}" --noprofile --driver {DRIVER} --device "{DEVICE}" --dpi {DPI} --bitdepth {BITDEPTH} --source {SOURCE} --pagesize {PAGESIZE} -f
autocolor=on
colormode=Color24
custompreset=
