// =============================================================================
// NextScan Studio - the reference the assistant reads about Word's API
// Plan ref: docs/DOCUMENT_WORKSPACE.md
//
// The assistant can change anything in a Word document, because edit_document
// runs a script for the editor's own document API. What stops a model from doing
// it well is not the power but the memory: it half remembers a dozen APIs, and
// this one's names, units and quirks (a paragraph's AddHyperlink replaces its
// text; sizes are half-points; a section break settles what came BEFORE it) are
// its own. So it asks: word_api gives it, on request, the recipes below -- each
// one tried in the running editor -- and the method list of any class, taken from
// the editor itself (GENERATED from it: do not edit the lists by hand; the recipes
// are recipes.txt of the same run).
// =============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace NextScan.App
{
    public static class StudioWordApi
    {
        // Method lists: class -> "Name/arguments Name/arguments ..." from the editor (version 9.4).
        static readonly string MethodText = @"Api: GetDocument/0 GetByInternalId/1 CreateParagraph/0 CreateRange/3 CreateTable/2 CreateNumbering/2 CreateRun/0 CreateHyperlink/3 CreateImage/3 CreateShape/5 CreateGroup/1 CreateChart/8 CreateOleObject/5 CreateCustomGeometry/0 CreatePresetGeometry/1 CreateRGBColor/3 CreateSchemeColor/1 CreatePresetColor/1 AutoColor/0 RGB/3 RGBA/4 HexColor/1 ThemeColor/1 Color/4 CreateSolidFill/1 CreateLinearGradientFill/2 CreateRadialGradientFill/1 CreatePatternFill/3 CreateBlipFill/2 CreateNoFill/0 CreateStroke/3 CreateGradientStop/2 CreateBullet/1 CreateInlineLvlSdt/0 CreateCheckBoxContentControl/1 CreatePictureContentControl/2 CreateComboBoxContentControl/2 CreateDropDownListContentControl/2 CreateDatePickerContentControl/1 CreateBlockLvlSdt/0 Save/0 LoadMailMergeData/1 GetMailMergeTemplateDocContent/0 GetMailMergeReceptionsCount/0 ReplaceDocumentContent/1 MailMerge/2 FromJSON/1 AddComment/4 ReplaceTextSmart/3 CoAuthoringChatSendMessage/1 ConvertDocument/5 CreateTextPr/0 CreateParaPr/0 CreateTablePr/0 CreateTableRowPr/0 CreateTableCellPr/0 CreateTableStylePr/1 CreateWordArt/8 GetFullName/0 PixelsToEmus/1 MillimetersToPixels/1 PointsToCentimeters/1 PointsToEmus/1 PointsToInches/1 PointsToLines/1 PointsToMillimeters/1 PointsToPicas/1 PointsToPixels/1 PointsToTwips/1 CentimetersToPoints/1 EmusToPoints/1 InchesToPoints/1 LinesToPoints/1 MillimetersToPoints/1 PicasToPoints/1 PixelsToPoints/1 TwipsToPoints/1 MillimetersToEmus/1 EmusToMillimeters/1 CompareDocuments/1 MergeDocuments/1 Px2Emu/1 Mm2Px/1 CreateTextForm/1 CreateCheckBoxForm/1 CreateComboBoxForm/1 CreatePictureForm/1 CreateSignatureForm/1 CreateDateForm/1 CreateComplexForm/1 AI/0
Document: GetClassType/0 CreateNewHistoryPoint/0 GetStyle/1 CreateStyle/2 GetDefaultStyle/1 GetDefaultTextPr/0 GetDefaultParaPr/0 GetFinalSection/0 CreateSection/1 SetEvenAndOddHdrFtr/1 CreateNumbering/1 InsertContent/3 GetCommentsReport/0 GetReviewReport/0 SearchAndReplace/1 GetAllContentControls/0 GetDrawingsByName/1 GetTagsOfAllContentControls/0 GetTagsOfAllForms/0 GetContentControlsByTag/1 GetFormsByTag/1 GetFormsByRole/1 GetFormsByKey/1 GetFormKeysByRole/1 GetFormValueByKey/1 GetFormsData/0 SetFormsData/1 SetTrackRevisions/1 SetAssistantTrackRevisions/2 IsTrackRevisions/0 GetRange/2 GetRangeBySelect/0 Last/0 DeleteBookmark/1 GetBookmarkRange/1 GetSections/0 GetAllTablesOnPage/1 AddDrawingToPage/4 RemoveSelection/0 Search/2 ToMarkdown/4 ToHtml/4 InsertWatermark/2 GetWatermarkSettings/0 SetWatermarkSettings/1 RemoveWatermark/0 UpdateAllTOC/1 UpdateAllTOF/1 UpdateAllFields/1 ToJSON/6 GetAllForms/0 ClearAllFields/0 SetFormsHighlight/1 GetFormsHighlight/0 GetAllComments/0 GetCommentById/1 ShowComment/1 GetAllNumberedParagraphs/0 GetAllHeadingParagraphs/0 GetFootnotesFirstParagraphs/0 GetEndNotesFirstParagraphs/0 GetAllCaptionParagraphs/1 AcceptAllRevisionChanges/0 RejectAllRevisionChanges/0 GetAllBookmarksNames/0 GetBookmark/1 GetSelectedDrawings/0 ReplaceCurrentImage/3 ReplaceDrawing/3 AddFootnote/0 AddEndnote/0 SetControlsHighlight/1 GetControlsHighlight/0 AddTableOfContents/1 AddTableOfFigures/2 GetStatistics/0 GetPageCount/0 GetCurrentPage/0 GetCurrentVisiblePages/0 GetAllStyles/0 GetDocumentInfo/0 GetCurrentWord/1 ReplaceCurrentWord/2 SelectCurrentWord/0 AddComment/3 GetCurrentSentence/1 ReplaceCurrentSentence/2 AddMathEquation/2 GroupDrawings/1 MoveCursorToPos/1 AddCheckBoxContentControl/1 AddPictureContentControl/2 AddComboBoxContentControl/2 AddDropDownListContentControl/2 AddDatePickerContentControl/1 GetCustomXmlParts/0 GetCore/0 GetCustomProperties/0 InsertBlankPage/0 MoveCursorToStart/0 MoveCursorToEnd/0 EnterText/1 InsertParagraphBreak/0 MoveCursorLeft/3 MoveCursorRight/3 MoveCursorUp/2 MoveCursorDown/2 GoToPage/1 GetCurrentFootEndnote/0 CreateTable/2 CreateParagraph/0 GetInternalId/0 Push/1 OnChangeParaPr/1 OnChangeTextPr/1 ForceRecalculate/1 InsertTextForm/1 GetFormRoles/0 GetElementsCount/0 GetElement/1 AddElement/2 RemoveAllElements/0 RemoveElement/1 GetContent/1 GetAllDrawingObjects/0 GetAllShapes/0 GetAllImages/0 GetAllCharts/0 GetAllOleObjects/0 GetAllParagraphs/0 GetAllTables/0 GetText/1 SetText/1 GetCurrentParagraph/0 GetCurrentRun/0 GetCurrentContentControl/0 IsFootnote/0 IsEndnote/0 SelectNoteReference/0 MoveCursorToNoteReference/1 AddParagraph/0 AddText/1
Section: GetClassType/0 SetType/1 GetType/0 SetEqualColumns/2 SetNotEqualColumns/2 GetColumnsCount/0 GetColumnsWidths/0 GetColumnsSpaces/0 SetPageSize/3 GetPageHeight/0 GetPageWidth/0 SetPageMargins/4 GetPageMarginLeft/0 GetPageMarginTop/0 GetPageMarginRight/0 GetPageMarginBottom/0 SetHeaderDistance/1 GetHeaderDistance/0 SetFooterDistance/1 GetFooterDistance/0 GetHeader/2 RemoveHeader/1 GetFooter/2 RemoveFooter/1 SetTitlePage/1 GetNext/0 GetPrevious/0 ToJSON/2 SetStartPageNumber/1 GetStartPageNumber/0 SetMargins/4
Paragraph: GetClassType/0 SetParaId/1 GetParaId/0 GetInternalId/0 AddText/1 AddPageBreak/0 AddLineBreak/0 AddColumnBreak/0 AddPageNumber/0 AddPagesCount/0 GetParagraphMarkTextPr/0 GetParaPr/0 GetNumbering/0 SetNumbering/1 GetElementsCount/0 GetElement/1 RemoveElement/1 RemoveAllElements/0 Delete/0 GetNext/0 GetPrevious/0 Copy/0 AddElement/2 AddTabStop/0 AddDrawing/1 AddInlineLvlSdt/1 AddComment/3 AddHyperlink/3 GetRange/2 Push/1 GetLastRunWithText/0 SetBold/1 SetCaps/1 SetColor/1 SetDoubleStrikeout/1 SetFontFamily/1 GetFontNames/0 SetFontSize/1 SetHighlight/1 SetItalic/1 SetPosition/1 SetSmallCaps/1 SetSpacing/1 SetStrikeout/1 SetUnderline/1 SetVertAlign/1 SetReadingOrder/1 Last/0 GetAllContentControls/0 GetAllDrawingObjects/0 GetAllShapes/0 GetAllImages/0 GetAllCharts/0 GetAllOleObjects/0 GetParentContentControl/0 GetParentTable/0 GetParentTableCell/0 GetText/1 SetText/1 GetTextPr/0 SetTextPr/1 InsertInContentControl/1 InsertParagraph/3 Select/0 Search/2 WrapInMailMergeField/0 AddNumberedCrossRef/5 AddHeadingCrossRef/4 AddBookmarkCrossRef/5 AddFootnoteCrossRef/4 AddEndnoteCrossRef/4 AddCaptionCrossRef/5 ToJSON/2 GetPosInParent/0 ReplaceByElement/1 AddCaption/7 GetSection/0 SetSection/1 AddPageBreakBefore/0 SetShd/2 OnChangeParaPr/1 OnChangeTextPr/1 SetStyle/1 GetStyle/0 SetContextualSpacing/1 GetContextualSpacing/0 SetIndLeft/1 GetIndLeft/0 SetIndRight/1 GetIndRight/0 SetIndFirstLine/1 GetIndFirstLine/0 SetJc/1 GetJc/0 SetKeepLines/1 GetKeepLines/0 SetKeepNext/1 GetKeepNext/0 SetPageBreakBefore/1 GetPageBreakBefore/0 SetSpacingLine/2 GetSpacingLineValue/0 GetSpacingLineRule/0 SetSpacingBefore/2 GetSpacingBefore/0 SetSpacingAfter/2 GetSpacingAfter/0 GetShd/0 SetBottomBorder/6 GetBottomBorder/0 SetLeftBorder/6 GetLeftBorder/0 SetRightBorder/6 GetRightBorder/0 SetTopBorder/6 GetTopBorder/0 SetBetweenBorder/6 GetBetweenBorder/0 SetWidowControl/1 GetWidowControl/0 SetTabs/2 GetTabs/0 SetNumPr/2 GetNumPr/0 SetBullet/1 SetOutlineLvl/1 GetOutlineLvl/0 GetEffectiveParaPr/0
Run: GetClassType/0 GetTextPr/0 ClearContent/0 RemoveAllElements/0 Delete/0 AddText/1 AddPageBreak/0 AddLineBreak/0 AddColumnBreak/0 AddTabStop/0 AddDrawing/1 Select/0 AddHyperlink/3 Copy/0 GetRange/2 GetParentContentControl/0 GetParentTable/0 GetParentTableCell/0 GetParentParagraph/0 SetTextPr/1 SetBold/1 SetCaps/1 SetColor/1 SetDoubleStrikeout/1 SetFill/1 SetFontFamily/1 GetFontNames/0 SetFontSize/1 SetHighlight/1 SetItalic/1 SetLanguage/1 SetPosition/1 SetShd/2 SetSmallCaps/1 SetSpacing/1 SetStrikeout/1 SetStyle/1 SetUnderline/1 SetVertAlign/1 WrapInMailMergeField/0 ToJSON/1 AddComment/3 GetText/1 MoveCursorToPos/1 OnChangeTextPr/1 GetStyle/0 GetBold/0 GetItalic/0 GetStrikeout/0 GetUnderline/0 GetFontFamily/1 GetFontSize/0 GetColor/0 GetVertAlign/0 GetHighlight/0 GetSpacing/0 GetDoubleStrikeout/0 GetCaps/0 GetSmallCaps/0 GetPosition/0 GetLanguage/0 GetShd/0 GetFill/0 SetTextFill/1 GetTextFill/0 SetOutLine/1 GetOutLine/0
Range: GetClassType/0 GetParagraph/1 AddText/2 AddBookmark/1 AddHyperlink/3 GetText/1 GetAllParagraphs/0 Select/1 ExpandTo/1 IntersectWith/1 SetBold/1 SetCaps/1 SetColor/1 SetDoubleStrikeout/1 SetHighlight/1 SetShd/2 SetItalic/1 SetStrikeout/1 SetSmallCaps/1 SetSpacing/1 SetUnderline/1 SetVertAlign/1 SetPosition/1 SetFontSize/1 SetFontFamily/1 SetStyle/1 SetTextPr/1 GetTextPr/0 Delete/0 ToJSON/2 AddComment/3 GetRange/2 GetStartPage/0 GetEndPage/0 SetStartPos/1 SetEndPos/1 GetStartPos/0 GetEndPos/0 MoveCursorToPos/1 AddField/1 OnChangeTextPr/1
Table: GetClassType/0 GetInternalId/0 GetRowsCount/0 GetRow/1 GetCell/2 MergeCells/1 SetStyle/1 SetTableLook/6 Split/3 AddRow/2 AddRows/3 AddColumn/2 AddColumns/3 AddElement/3 RemoveRow/1 RemoveColumn/1 Copy/0 Select/0 GetRange/2 SetHAlign/1 SetVAlign/1 SetPaddings/4 SetWrappingStyle/1 GetParentContentControl/0 InsertInContentControl/1 GetParentTable/0 GetTables/0 GetParentTableCell/0 Delete/0 Clear/0 Search/2 SetTextPr/1 SetBackgroundColor/1 ToJSON/2 GetPosInParent/0 ReplaceByElement/1 AddComment/3 AddCaption/7 GetAllCells/0 SetJc/1 OnChangeTablePr/1 SetStyleColBandSize/1 SetStyleRowBandSize/1 SetShd/5 SetTableBorderTop/6 SetTableBorderBottom/6 SetTableBorderLeft/6 SetTableBorderRight/6 SetTableBorderInsideH/6 SetTableBorderInsideV/6 SetTableBorderAll/6 SetTableCellMarginBottom/1 SetTableCellMarginLeft/1 SetTableCellMarginRight/1 SetTableCellMarginTop/1 SetCellSpacing/1 SetTableInd/1 SetWidth/2 SetTableLayout/1 SetTableTitle/1 GetTableTitle/0 SetTableDescription/1 GetTableDescription/0
Row: GetClassType/0 GetInternalId/0 GetCellsCount/0 GetCell/1 GetIndex/0 GetParentTable/0 GetNext/0 GetPrevious/0 AddRows/2 MergeCells/0 Clear/0 Remove/0 SetTextPr/1 Search/2 SetBackgroundColor/1 OnChangeTableRowPr/1 SetHeight/2 SetTableHeader/1 ToJSON/0
Cell: GetClassType/0 GetInternalId/0 GetContent/0 GetIndex/0 GetRowIndex/0 GetParentRow/0 GetParentTable/0 AddRows/2 AddColumns/2 RemoveColumn/0 RemoveRow/0 Search/2 GetNext/0 GetPrevious/0 Split/2 SetCellPr/1 SetTextPr/1 Clear/0 AddElement/2 SetBackgroundColor/1 GetBackgroundColor/0 SetColumnBackgroundColor/1 AddText/1 GetText/1 SetText/1 OnChangeTableCellPr/1 SetShd/5 SetCellMarginBottom/1 SetCellMarginLeft/1 SetCellMarginRight/1 SetCellMarginTop/1 SetCellBorderBottom/6 SetCellBorderLeft/6 SetCellBorderRight/6 SetCellBorderTop/6 SetWidth/2 SetVerticalAlign/1 SetTextDirection/1 SetNoWrap/1 ToJSON/0
TextPr: GetClassType/0 SetStyle/1 GetStyle/0 SetBold/1 GetBold/0 SetItalic/1 GetItalic/0 SetStrikeout/1 GetStrikeout/0 SetUnderline/1 GetUnderline/0 SetFontFamily/1 GetFontFamily/1 SetFontSize/1 GetFontSize/0 SetColor/1 GetColor/0 SetVertAlign/1 GetVertAlign/0 SetHighlight/1 GetHighlight/0 SetSpacing/1 GetSpacing/0 SetDoubleStrikeout/1 GetDoubleStrikeout/0 SetCaps/1 GetCaps/0 SetSmallCaps/1 GetSmallCaps/0 SetPosition/1 GetPosition/0 SetLanguage/1 GetLanguage/0 SetShd/2 GetShd/0 SetFill/1 GetFill/0 SetTextFill/1 GetTextFill/0 SetOutLine/1 GetOutLine/0 ToJSON/1
ParaPr: GetClassType/0 SetStyle/1 GetStyle/0 SetContextualSpacing/1 GetContextualSpacing/0 SetIndLeft/1 GetIndLeft/0 SetIndRight/1 GetIndRight/0 SetIndFirstLine/1 GetIndFirstLine/0 SetJc/1 GetJc/0 SetKeepLines/1 GetKeepLines/0 SetKeepNext/1 GetKeepNext/0 SetPageBreakBefore/1 GetPageBreakBefore/0 SetSpacingLine/2 GetSpacingLineValue/0 GetSpacingLineRule/0 SetSpacingBefore/2 GetSpacingBefore/0 SetSpacingAfter/2 GetSpacingAfter/0 SetShd/2 GetShd/0 SetBottomBorder/6 GetBottomBorder/0 SetLeftBorder/6 GetLeftBorder/0 SetRightBorder/6 GetRightBorder/0 SetTopBorder/6 GetTopBorder/0 SetBetweenBorder/6 GetBetweenBorder/0 SetWidowControl/1 GetWidowControl/0 SetTabs/2 GetTabs/0 SetNumPr/2 GetNumPr/0 SetBullet/1 SetOutlineLvl/1 GetOutlineLvl/0 ToJSON/1 GetEffectiveParaPr/0
Style: GetClassType/0 GetName/0 SetName/1 GetType/0 GetTextPr/0 SetTextPr/1 GetParaPr/0 SetParaPr/1 GetTablePr/0 SetTablePr/1 GetTableRowPr/0 SetTableRowPr/1 GetTableCellPr/0 SetTableCellPr/1 SetBasedOn/1 GetConditionalTableStyle/1 SetConditionalTableStyle/1 ToJSON/1 OnChangeTextPr/1 OnChangeParaPr/1 OnChangeTablePr/1 OnChangeTableRowPr/1 OnChangeTableCellPr/1 OnChangeTableStylePr/1
Shape: GetClassType/0 GetDocContent/0 SetVerticalTextAlign/1 SetPaddings/4 GetNextShape/0 GetPrevShape/0 GetGeometry/0 SetGeometry/1 SetFill/1 GetFill/0 SetLine/1 GetLine/0 GetContent/0 SetSize/2 SetRelativeHeight/2 SetRelativeWidth/2 SetWrappingStyle/1 SetHorAlign/2 SetVerAlign/2 SetHorPosition/3 SetVerPosition/3 SetDistances/4 GetParentParagraph/0 GetParentContentControl/0 GetParentTable/0 GetParentTableCell/0 Delete/0 Copy/0 InsertInContentControl/1 InsertParagraph/3 Select/1 Unselect/0 AddBreak/2 GetFlipH/0 GetFlipV/0 SetFlipH/1 SetFlipV/1 SetHorFlip/1 SetVertFlip/1 ScaleHeight/1 ScaleWidth/1 Fill/1 SetOutLine/1 GetNextDrawing/0 GetPrevDrawing/0 ToJSON/2 GetWidth/0 GetHeight/0 GetName/0 SetName/1 GetLockValue/1 SetLockValue/2 SetDrawingPrFromDrawing/1 SetRotation/1 GetRotation/0
Chart: GetClassType/0 GetChartType/0 SetTitle/3 GetTitle/0 SetHorAxisTitle/3 SetVerAxisTitle/3 SetVerAxisOrientation/1 SetHorAxisOrientation/1 SetLegendPos/1 SetLegendFontSize/1 SetShowDataLabels/4 SetShowPointDataLabel/6 SetVertAxisTickLabelPosition/1 SetHorAxisTickLabelPosition/1 SetHorAxisMajorTickMark/1 SetHorAxisMinorTickMark/1 SetVertAxisMajorTickMark/1 SetVertAxisMinorTickMark/1 SetMajorVerticalGridlines/1 SetMinorVerticalGridlines/1 SetMajorHorizontalGridlines/1 SetMinorHorizontalGridlines/1 SetHorAxisLabelsFontSize/1 SetVertAxisLabelsFontSize/1 GetNextChart/0 GetPrevChart/0 RemoveSeria/1 SetSeriaValues/2 SetXValues/1 SetSeriaName/2 SetCategoryName/2 ApplyChartStyle/1 SetPlotAreaFill/1 SetPlotAreaOutLine/1 SetSeriesFill/3 SetSeriesOutLine/3 SetDataPointFill/4 SetDataPointOutLine/4 SetMarkerFill/4 SetMarkerOutLine/4 SetTitleFill/1 SetTitleOutLine/1 SetLegendFill/1 SetLegendOutLine/1 SetAxieNumFormat/2 SetSeriaNumFormat/2 SetDataPointNumFormat/4 GetAllSeries/0 GetSeries/1 SetHorAxisLablesFontSize/1 SetVertAxisLablesFontSize/1 GetContent/0 SetSize/2 SetRelativeHeight/2 SetRelativeWidth/2 SetWrappingStyle/1 SetHorAlign/2 SetVerAlign/2 SetHorPosition/3 SetVerPosition/3 SetDistances/4 GetParentParagraph/0 GetParentContentControl/0 GetParentTable/0 GetParentTableCell/0 Delete/0 Copy/0 InsertInContentControl/1 InsertParagraph/3 Select/1 Unselect/0 AddBreak/2 GetFlipH/0 GetFlipV/0 SetFlipH/1 SetFlipV/1 SetHorFlip/1 SetVertFlip/1 ScaleHeight/1 ScaleWidth/1 Fill/1 SetOutLine/1 GetNextDrawing/0 GetPrevDrawing/0 ToJSON/2 GetWidth/0 GetHeight/0 GetName/0 SetName/1 GetLockValue/1 SetLockValue/2 SetDrawingPrFromDrawing/1 SetRotation/1 GetRotation/0
Image: GetClassType/0 GetNextImage/0 GetPrevImage/0 GetContent/0 SetSize/2 SetRelativeHeight/2 SetRelativeWidth/2 SetWrappingStyle/1 SetHorAlign/2 SetVerAlign/2 SetHorPosition/3 SetVerPosition/3 SetDistances/4 GetParentParagraph/0 GetParentContentControl/0 GetParentTable/0 GetParentTableCell/0 Delete/0 Copy/0 InsertInContentControl/1 InsertParagraph/3 Select/1 Unselect/0 AddBreak/2 GetFlipH/0 GetFlipV/0 SetFlipH/1 SetFlipV/1 SetHorFlip/1 SetVertFlip/1 ScaleHeight/1 ScaleWidth/1 Fill/1 SetOutLine/1 GetNextDrawing/0 GetPrevDrawing/0 ToJSON/2 GetWidth/0 GetHeight/0 GetName/0 SetName/1 GetLockValue/1 SetLockValue/2 SetDrawingPrFromDrawing/1 SetRotation/1 GetRotation/0
Hyperlink: GetClassType/0 SetLink/1 SetDisplayedText/1 SetScreenTipText/1 GetLinkedText/0 GetDisplayedText/0 GetScreenTipText/0 GetElement/1 GetElementsCount/0 SetDefaultStyle/0 GetRange/2 ToJSON/1
Numbering: GetClassType/0 GetLevel/1 ToJSON/0
NumberingLevel: GetClassType/0 GetNumbering/0 GetLevelIndex/0 GetTextPr/0 GetParaPr/0 SetTemplateType/2 SetCustomType/3 SetRestart/1 SetStart/1 SetSuff/1 LinkWithStyle/1 OnChangeTextPr/1 OnChangeParaPr/1
DocumentContent: GetClassType/0 GetInternalId/0 GetElementsCount/0 GetElement/1 AddElement/2 Push/1 RemoveAllElements/0 RemoveElement/1 GetRange/2 ToJSON/2 GetContent/1 GetAllDrawingObjects/0 GetAllShapes/0 GetAllImages/0 GetAllCharts/0 GetAllOleObjects/0 GetAllParagraphs/0 GetAllTables/0 GetText/1 SetText/1 GetCurrentParagraph/0 GetCurrentRun/0 GetCurrentContentControl/0 IsFootnote/0 IsEndnote/0 SelectNoteReference/0 MoveCursorToNoteReference/1 AddParagraph/0 AddText/1
TablePr: GetClassType/0 SetStyleColBandSize/1 SetStyleRowBandSize/1 SetJc/1 SetShd/5 SetTableBorderTop/6 SetTableBorderBottom/6 SetTableBorderLeft/6 SetTableBorderRight/6 SetTableBorderInsideH/6 SetTableBorderInsideV/6 SetTableBorderAll/6 SetTableCellMarginBottom/1 SetTableCellMarginLeft/1 SetTableCellMarginRight/1 SetTableCellMarginTop/1 SetCellSpacing/1 SetTableInd/1 SetWidth/2 SetTableLayout/1 SetTableTitle/1 GetTableTitle/0 SetTableDescription/1 GetTableDescription/0 ToJSON/0
TableCellPr: GetClassType/0 SetShd/5 SetCellMarginBottom/1 SetCellMarginLeft/1 SetCellMarginRight/1 SetCellMarginTop/1 SetCellBorderBottom/6 SetCellBorderLeft/6 SetCellBorderRight/6 SetCellBorderTop/6 SetWidth/2 SetVerticalAlign/1 SetTextDirection/1 SetNoWrap/1 ToJSON/0
ContentControl: GetClassType/0 GetInternalId/0 SetId/1 GetId/0 SetLock/1 GetLock/0 SetTag/1 GetTag/0 SetLabel/1 GetLabel/0 SetAlias/1 GetAlias/0 GetElementsCount/0 GetElement/1 RemoveElement/1 RemoveAllElements/0 AddElement/2 Push/1 AddText/1 Delete/1 SetTextPr/1 GetParentParagraph/0 GetParentContentControl/0 GetParentTable/0 GetParentTableCell/0 GetRange/2 Copy/0 ToJSON/1 GetPlaceholderText/0 SetPlaceholderText/1 IsForm/0 AddComment/3 MoveCursorOutside/1 GetDropdownList/0 SetBorderColor/1 GetBorderColor/0 SetBackgroundColor/1 GetBackgroundColor/0 Select/0 SetDataBinding/1 GetDataBinding/0 UpdateFromXmlMapping/0 GetDataForXmlMapping/0 IsCheckBox/0 SetCheckBoxChecked/1 IsCheckBoxChecked/0 IsPicture/0 SetPictureSize/2 SetPicture/1 IsDropDownList/0 IsComboBox/0 SelectListItem/1 AddListItem/3 RemoveListItem/1 IsDatePicker/0 SetDate/1 GetDate/0 SetDateFormat/1 SetAppearance/1 GetAppearance/0 SetColor/1 GetColor/0
Fill: GetClassType/0 ToJSON/0 GetType/0
Stroke: GetClassType/0 ToJSON/0 GetWidth/0 GetFill/0 GetDashType/0
";

        // Recipes: "## topic" then text.
        static readonly string RecipeText = @"## overview
Word's document API is ONLYOFFICE's Office JavaScript API. Three ways to use it, easiest first:
1. write_document / format_document take a description (mm and pt); they cover most of what a page has: fonts, sizes, spacing, columns, sections, headers and footers, page numbers, lists, numbered headings, styles, tables, pictures, shapes, charts, equations, contents pages, footnotes, links, watermarks. Ask word_api with topic 'write' for the full vocabulary.
2. edit_document runs a script for the API itself: everything the editor can do. Inside it the kit NS is there: NS.tw(mm), NS.ptw(pt), NS.emu(mm) turn measurements into the API's units, NS.paragraph(spec), NS.table(spec), NS.textbox(spec), NS.chart(spec), NS.list(spec, null, doc), NS.format(spec), NS.latex('\frac{a}{b}') (LaTeX to the editor's equation form).
3. word_api with a class name (Document, Section, Paragraph, Run, Range, Table, Cell, Row, Style, Shape, Chart, Image, Hyperlink, Numbering, NumberingLevel, DocumentContent, TextPr, ParaPr, TablePr, TableCellPr, ContentControl, Api) lists that class's methods, with how many arguments each takes. Use it when you need a call the recipes do not show. The names are exactly this editor's, and case matters.
UNITS in the raw API: spacing, indents, page size and margins are TWIPS (1 mm = 56.7, 1 pt = 20); font sizes are HALF-POINTS (12 pt = 24); drawing sizes and positions are EMU (1 mm = 36000); colours are three numbers, e.g. p.SetColor(31, 78, 121, false).
Elements: doc.GetElement(i) is the i-th top-level block (a paragraph or a table); doc.GetElementsCount(); doc.Push(element) adds at the end; doc.AddElement(i, element) inserts; doc.RemoveElement(i).
Always look at the result afterwards (look_at_document): a call that runs without error can still look wrong.
## write
write_document / format_document description, all in mm, pt, '#RRGGBB'.
page: {size:'A4'|[w,h], orientation, margins:[top,right,bottom,left], columns: 2 | {count, gap} | {widths:[..], gaps:[..]}, header, footer, firstHeader, firstFooter, evenHeader, evenFooter (each: a string, a paragraph {text|runs, align, tabs, size...}, a list of them, or {blocks:[...]}), differentFirstPage, headerDistance, footerDistance, startNumber, watermark:'DRAFT' (or false to remove)}.
runs, in a paragraph or a header/footer: {text, bold, italic, underline, strike, font, size, color, highlight, caps, smallCaps, spacing, vertAlign:'superscript'|'subscript'}, {page:true} the page number, {pages:true} the page count, {text:'label', link:'https://...'} a hyperlink.
paragraph also: footnote:'text' (a footnote at the end of the paragraph).
blocks: paragraph, heading {level}, list {kind:'bullet'|'number'|'lower-alpha'|'upper-alpha'|'lower-roman'|'upper-roman', bullet:'-', start, items:['text' | {text, level:0-8}], indent:{left, hanging}}, table, image, textbox, shape {shape:'ellipse'|'roundRect'|'triangle'|'diamond'|'rightArrow'|'star5'|'line'|..., width, height, fill, line:{color,size}, rotation, text, x, y}, chart {chart:'column'|'bar'|'line'|'pie'|'doughnut'|'area'|'scatter'|'columnStacked'..., title, categories:[..], series:[{name, values:[..]}], width, height, legend, colors:[..], dataLabels, xTitle, yTitle}, equation {text: LaTeX or linear form}, toc {levels, dots, pageNumbers}, section_break {kind:'nextPage'|'continuous'|'oddPage'|'evenPage', page:{...}, columns} (what comes AFTER the break takes the new page setup and columns), column_break, spacer, page_break.
styles: {'Normal': {font,size,color,bold,italic,before,after,line,align,indent...}, 'Heading 1': {...}, 'Title': {...}} changes a named style for the whole document. headingNumbers: true | {levels: 3} numbers Heading 1/2/3 as 1. / 1.1. / 1.1.1.
defaults: {font, size, color, after, before, line} the body text of the document.
format_document changes what is there without rewriting: target {all:true} | {blocks:[from,to]} | {style:'Heading 1'} | {tables:true} | {text:'find', matchCase}, set {font,size,bold,italic,underline,color,highlight,align,before,after,line,indent,style,fill,...}, replace {find, with, matchCase}; and the same page, defaults, styles, headingNumbers.
## fonts
Face and size, at every level:
- a paragraph, run or found range: p.SetFontFamily('Arial'); p.SetFontSize(24) (half-points: 12 pt); p.SetBold(true); p.SetItalic(true); p.SetUnderline(true); p.SetStrikeout(true); p.SetColor(31,78,121,false); p.SetHighlight('yellow'); p.SetCaps(true); p.SetSmallCaps(true); p.SetSpacing(NS.ptw(1)) (space between letters); p.SetVertAlign('superscript'); paragraph setters format all the text in it.
- everything: format_document {target:{all:true}, set:{font:'Arial', size:12}}.
- the document's default: var tp = doc.GetDefaultTextPr(); tp.SetFontFamily('Times New Roman'); tp.SetFontSize(24);
- a named style: doc.GetStyle('Normal').GetTextPr().SetFontSize(22); doc.GetStyle('Heading 1').GetTextPr().SetColor(31,78,121,false).
- one word: var found = doc.Search('word', true); found[0].SetBold(true).
Fonts: a name the machine does not have is replaced by another when it prints; look_at_document shows what is really drawn. Bengali: 'Nirmala UI' for Unicode Bengali text; a legacy Bijoy font such as 'SutonnyMJ' only holds text that was typed in that font.
## page
Page setup is on the section: var s = doc.GetFinalSection(); s.SetPageSize(NS.tw(210), NS.tw(297), true) (width, height, portrait?); s.SetPageMargins(left, top, right, bottom) in twips (that order); s.SetHeaderDistance(twips); s.SetFooterDistance(twips); s.SetTitlePage(true) (different first page); s.SetStartPageNumber(n). Or write_document page: {...} in mm. Landscape: page:{orientation:'landscape'} turns the page the section already has. Page borders are not in the API.
## columns
write_document page:{columns:2} or {columns:{count:3, gap:8}} or {columns:{widths:[60,100], gaps:[10]}} (mm). Raw: var s = doc.GetFinalSection(); s.SetEqualColumns(2, NS.tw(10)); s.SetNotEqualColumns([NS.tw(60), NS.tw(100)], [NS.tw(10)]). A column break: {type:'column_break'} or p.AddColumnBreak(). Different columns on different parts of a document: put a {type:'section_break', kind:'continuous', columns:2} where the two-column part starts and another {type:'section_break', kind:'continuous', columns:1} where it ends. There is no line between columns in the API.
## sections
A section is a run of pages with its own page size, orientation, margins, columns, headers. {type:'section_break', kind:'nextPage'|'continuous', page:{orientation:'landscape'}, columns:2}: everything after the break uses those settings; what came before keeps its own. Raw: var ended = doc.CreateSection(paragraph) ends a section at that paragraph (the paragraph must already be in the document; ended has the settings the section had); after it doc.GetFinalSection() is the one that follows: set its SetType('continuous'), SetPageSize, SetEqualColumns... doc.GetSections() lists them.
## headers_footers
write_document page:{header:{runs:[{text:'Title', bold:true},{text:'\t'},{text:'Page '},{page:true},{text:' of '},{pages:true}], tabs:[{pos:165, align:'right'}]}, footer:'Confidential'}. A different first page: differentFirstPage:true with firstHeader / firstFooter; different odd and even: evenHeader / evenFooter. Raw: var h = doc.GetFinalSection().GetHeader('default', true) (or GetFooter; 'first', 'even'); it is a document-content object: h.RemoveAllElements(); var p = h.GetElement(0); p.AddText('text'); p.AddPageNumber(); p.AddPagesCount(); p.SetJc('center'). doc.SetEvenAndOddHdrFtr(true) turns on odd/even. s.RemoveHeader('default') / s.RemoveFooter('default') remove them. Page number fields need a paragraph: p.AddPageNumber() is not a run, so style the paragraph (p.SetFontSize) rather than a run.
## headings
Headings are paragraphs with a style: {type:'heading', level:1, text} or p.SetStyle(doc.GetStyle('Heading 1')). Look of a heading level: styles:{'Heading 1':{font:'Georgia', size:20, bold:true, color:'#1F4E79', before:12, after:6}}. Numbered headings 1. / 1.1.: headingNumbers:true, or raw: var n = doc.CreateNumbering('numbered'); n.GetLevel(0).SetCustomType('decimal', '%1.', 'left'); n.GetLevel(1).SetCustomType('decimal', '%1.%2.', 'left'); n.GetLevel(0).LinkWithStyle(doc.GetStyle('Heading 1')); n.GetLevel(1).LinkWithStyle(doc.GetStyle('Heading 2')). Outline level of any paragraph (what a contents page collects): p.SetOutlineLvl(0). A contents page: {type:'toc', levels:3}; raw: paragraph.Select(); doc.AddTableOfContents({ShowPageNums:true, RightAlgn:true, LeaderType:'dot', FormatAsLinks:true, BuildFrom:{OutlineLvls:3}, TocStyle:'standard'}); then doc.UpdateAllTOC(). It lists only headings that exist when it is made or updated.
## styles
doc.GetStyle('Normal') / 'Heading 1' / 'Title' / 'Subtitle' / 'List Paragraph' / 'Caption' ...; doc.GetAllStyles() lists them; doc.CreateStyle('My style'). A style has GetTextPr() and GetParaPr(): st.GetTextPr().SetFontSize(28); st.GetParaPr().SetSpacingAfter(NS.ptw(6)); st.GetParaPr().SetJc('center'). Apply: p.SetStyle(st). write_document styles:{name:{font,size,color,bold,before,after,line,align,indent,keepNext...}}. A paragraph's own formatting overrides its style.
## lists
{type:'list', kind:'bullet'|'number'|'lower-alpha'|'upper-roman', items:['One', {text:'Nested', level:1}]}. Raw: var n = doc.CreateNumbering('bullet' | 'numbered'); var l0 = n.GetLevel(0); l0.SetTemplateType('1.', '') (formats '1.', '1)', 'a)', 'A.', 'i.', 'I.'; for a bullet: 'bullet' with the symbol as the second argument); l0.GetParaPr().SetIndLeft(NS.tw(10)); p.SetNumbering(l0) makes p an item of that list at that level; a new CreateNumbering starts a new list at 1. l0.SetStart(5) starts at 5.
## shapes
{type:'shape', shape:'roundRect', width:60, height:20, fill:'#FFF2CC', line:{color:'#BF9000', size:1}, text:'Label', align:'center', valign:'center', x:20, y:100} (x, y in mm from the page corner make it float; without them it sits in the text). Shape names: rect, roundRect, ellipse, triangle, rtTriangle, diamond, parallelogram, trapezoid, pentagon, hexagon, octagon, star5, star8, rightArrow, leftArrow, upArrow, downArrow, chevron, plus, heart, cloud, sun, moon, line, wedgeRectCallout, flowChartProcess, flowChartDecision. Text inside a shape is black unless you give color. Raw: var sh = Api.CreateShape('ellipse', NS.emu(40), NS.emu(20), Api.CreateSolidFill(Api.CreateRGBColor(255,200,0)), Api.CreateStroke(12700, Api.CreateSolidFill(Api.CreateRGBColor(0,0,0)))); sh.GetDocContent().GetElement(0).AddText('x'); paragraph.AddDrawing(sh); floating: sh.SetWrappingStyle('inFront'); sh.SetHorPosition('page', NS.emu(20)); sh.SetVerPosition('page', NS.emu(100)); sh.SetRotation(30); Api.CreateGroup([shapes]) groups. Gradient: Api.CreateLinearGradientFill([Api.CreateGradientStop(color, pos)], angle). No fill: Api.CreateNoFill(). Line width in EMU (1 pt = 12700).
## charts
{type:'chart', chart:'column', title:'Sales', categories:['Q1','Q2','Q3'], series:[{name:'2025', values:[10,20,15]}, {name:'2026', values:[12,22,30]}], width:120, height:70, colors:['#1F4E79','#C55A11'], legend:'bottom', dataLabels:true, xTitle:'Quarter', yTitle:'Units'}. Types: column, columnStacked, columnPercent, bar (horizontal), barStacked, line, lineStacked, pie, pie3d, doughnut, area, areaStacked, scatter, stock. Raw: var c = Api.CreateChart('bar', [[10,20],[5,15]], ['A','B'], ['x','y'], NS.emu(120), NS.emu(70), 24); c.SetTitle('T', 14); c.SetLegendPos('bottom'); c.SetShowDataLabels(false,false,true,false); c.SetSeriesFill(Api.CreateSolidFill(Api.CreateRGBColor(31,78,121)), 0, false); c.SetHorAxisTitle('x', 11); c.SetVerAxisTitle('y', 11); c.SetPlotAreaFill(fill); c.ApplyChartStyle(n); paragraph.AddDrawing(c). (In a raw script the API's own type names are 'bar' (columns), 'horizontalBar', 'lineNormal', 'pie', 'doughnut', 'area', 'scatter'.)
## math
{type:'equation', text:'\frac{-b \pm \sqrt{b^2-4ac}}{2a}'}: LaTeX is converted (fractions, roots, powers, subscripts, sums, integrals, greek, common symbols); a plain linear form also works: '(a+b)/2', 'x^2+y^2=z^2', 'E=mc^2'. An equation takes its own line, centred. Raw: paragraph.Select(); doc.AddMathEquation(NS.latex('\sum_{i=1}^{n} i^2'), 'unicode'); the text is in the linear (UnicodeMath) form: a/b, x^2, x_i, symbols as themselves (the square root sign, sum sign, pi...), (..) for grouping. It replaces the selected paragraph's content. An equation inside a line of text cannot be made through the API: put it on its own line.
## footnotes
A paragraph with footnote:'The note text' gets a footnote at its end. Raw: paragraph.Select(); doc.MoveCursorRight(1,false,false); doc.MoveCursorLeft(1,false,false); var note = doc.AddFootnote(); note.GetElement(0).AddText(' the text'); (doc.AddEndnote() the same for an endnote). The cursor calls put the note at the end of that paragraph; in the document's last paragraph use doc.MoveCursorToEnd() instead.
## links
A hyperlink run: {text:'the site', link:'https://example.com', tip:'Screen tip'}. Raw: var h = Api.CreateHyperlink('https://example.com', 'the site', 'tip'); paragraph.AddElement(h). Do NOT use paragraph.AddHyperlink(...): it replaces the paragraph's text. A bookmark: doc.Search('text')[0].AddBookmark('name'); a link to it: Api.CreateHyperlink('#name', 'see there', '') (check that it lands).
## watermark
page:{watermark:'DRAFT'} (a grey diagonal text behind every page); false removes it. Raw: doc.InsertWatermark('DRAFT', true); doc.RemoveWatermark(); doc.GetWatermarkSettings() / SetWatermarkSettings(settings) for its font, size, colour, opacity.
## images
{type:'image', src:'C:\path\file.png' or a data: URL, width:60, height:40, align:'center'} or with x, y (mm) floating. Raw: var img = Api.CreateImage(dataUrl, NS.emu(60), NS.emu(40)); paragraph.AddDrawing(img); img.SetWrappingStyle('inline'|'square'|'tight'|'topAndBottom'|'behind'|'inFront'); img.SetHorPosition('page'|'margin'|'column', emu); img.SetVerPosition(...). Sizes are EMU. Keep the aspect ratio: work out the height from the picture's own.
## find
var found = doc.Search('text', matchCase) returns ranges: found.length; found[i].SetBold(true) etc.; found[i].GetText(); found[i].AddText(' more', 'after'); found[i].Delete(). Replace: doc.SearchAndReplace({searchString:'a', replaceString:'b', matchCase:true}). Or format_document {replace:{find:'a', with:'b'}}. Search covers the body, tables and text boxes' paragraphs.
## tables
{type:'table', columns:[60,60,60], rows:[...]} (see write). After: t.AddRow(rowIndex?, bAfter) / t.AddRows / t.AddColumn(cell?, after) / t.RemoveRow(i) / t.RemoveColumn(cell) / t.MergeCells([cells]); row.SetHeight('atLeast'|'exact', twips); row.SetTableHeader(true) repeats the row on each page; cell.SetBackgroundColor(r,g,b) or cell.SetShd('clear', r,g,b); cell.SetVerticalAlign('center'); cell.SetTextDirection('lrtb'|'tbrl'|'btlr'); t.SetTableBorderTop('single', size_eighths_pt, space, r,g,b) (and Bottom, Left, Right, InsideH, InsideV); t.SetWidth('twips', n) / ('percent', 100); t.SetTableLook(firstCol, firstRow, lastCol, lastRow, hBand, vBand) with t.SetStyle(style). Cell content: cell.GetContent() is a document-content object (GetElement(0), Push(paragraph)).
## tabs
p.SetTabs([NS.tw(60), NS.tw(165)], ['left', 'right']) (positions in twips from the left margin; types left, right, center, decimal, bar) and '\t' in the text (write_document paragraph: tabs:[{pos:165, align:'right'}]). A tab leader (dots up to the tab) cannot be set through the API: use a table cell with a dotted bottom border, or a run of dots.
## comments
range.AddComment('text', 'Author') or paragraph.AddComment(...); doc.GetAllComments(); doc.SetTrackRevisions(true) records later edits as tracked changes; doc.AcceptAllRevisionChanges() / RejectAllRevisionChanges(); doc.GetReviewReport().
## forms
Content controls: Api.CreateCheckBoxContentControl(), CreateComboBoxContentControl(items), CreateDropDownListContentControl(items), CreateDatePickerContentControl(), CreatePictureContentControl(), CreateInlineLvlSdt() (a text control; sdt.AddText(..)), CreateBlockLvlSdt(); Fill-in forms: Api.CreateTextForm({key, tip, required, placeholder, comb, maxCharacters, width, multiLine}), CreateCheckBoxForm, CreateComboBoxForm, CreateDateForm, CreatePictureForm. Add to a paragraph with paragraph.AddInlineLvlSdt(control) or paragraph.AddElement(form).
## direction
Right-to-left text: paragraph.SetReadingOrder('rtl'). Text direction in a table cell: cell.SetTextDirection('btlr'). Space between lines: p.SetSpacingLine(240, 'auto') is single, 360 is 1.5 lines; exact: p.SetSpacingLine(NS.ptw(14), 'exact'); before/after: p.SetSpacingBefore(NS.ptw(6)).
";

        static Dictionary<string, string> _classes, _topics;

        static void Load()
        {
            if (_classes != null) return;
            var classes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (string line in MethodText.Split('\n'))
            {
                int colon = line.IndexOf(':');
                if (colon > 0) classes[line.Substring(0, colon).Trim()] = line.Substring(colon + 1).Trim();
            }
            var topics = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            string name = null;
            var body = new StringBuilder();
            foreach (string line in RecipeText.Split('\n'))
            {
                if (line.StartsWith("## ", StringComparison.Ordinal))
                {
                    if (name != null) topics[name] = body.ToString().Trim();
                    name = line.Substring(3).Trim();
                    body.Length = 0;
                }
                else body.Append(line).Append('\n');
            }
            if (name != null) topics[name] = body.ToString().Trim();
            _topics = topics;
            _classes = classes;
        }

        /// <summary>The topics and classes there is something to say about.</summary>
        public static string Index()
        {
            Load();
            var sb = new StringBuilder();
            sb.Append("Topics (ask word_api with topic = one of these): ");
            foreach (string t in _topics.Keys) if (t != "overview") sb.Append(t).Append(", ");
            sb.Length -= 2;
            sb.Append(".\nClasses (their methods): ");
            foreach (string c in _classes.Keys) sb.Append(c).Append(", ");
            sb.Length -= 2;
            sb.Append(".\nOr give a word to search for in the method names, e.g. 'column', 'footnote', 'border'.");
            return sb.ToString();
        }

        /// <summary>The answer for a topic, a class or a word to look for.</summary>
        public static string Answer(string topic)
        {
            Load();
            topic = (topic ?? "").Trim();
            if (topic.Length == 0) return _topics["overview"] + "\n\n" + Index();

            string hit;
            if (_topics.TryGetValue(topic, out hit)) return hit;

            string cls = topic.StartsWith("Api", StringComparison.OrdinalIgnoreCase) && topic.Length > 3 && !_classes.ContainsKey(topic) ? topic.Substring(3) : topic;
            if (_classes.TryGetValue(cls, out hit))
                return cls + " methods, as Name/number of arguments (call as object.Name(...)): " + hit;

            // A word: the classes' methods with it in their name, and the topics that mention it.
            string needle = topic.ToLowerInvariant();
            var sb = new StringBuilder();
            foreach (var kv in _classes)
            {
                var found = new List<string>();
                foreach (string m in kv.Value.Split(' '))
                    if (m.ToLowerInvariant().Contains(needle)) found.Add(m);
                if (found.Count > 0) sb.Append(kv.Key).Append(": ").Append(string.Join(" ", found.ToArray())).Append('\n');
            }
            foreach (var kv in _topics)
                if (kv.Key != "overview" && kv.Value.ToLowerInvariant().Contains(needle)) sb.Append("Topic '").Append(kv.Key).Append("' mentions it.\n");
            if (sb.Length == 0) return "Nothing matches '" + topic + "'.\n" + Index();
            return "Matches for '" + topic + "' (Class: Name/number of arguments):\n" + sb.ToString().TrimEnd();
        }
    }
}
